---
# Per environment values which override defaults in hmpps-prisoner-contacts/values.yaml

generic-service:
  replicaCount: 0 # Leave this until the security question over visibility of contact data is decided

  ingress:
    host: prisoner-contacts.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://prisoner-contacts.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    PRISON_API_URL: "https://api.prison.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-offender-search.prison.service.justice.gov.uk"
