---
# Per environment values which override defaults in hmpps-prisoner-contacts/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: prisoner-contacts-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://prisoner-contacts-preprod.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    PRISON_API_URL: "https://api-preprod.prison.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-offender-search-preprod.prison.service.justice.gov.uk"
